name: Build and Push Image

on:
  workflow_call:
    inputs:
      platforms:
        description: 'Target platforms (comma-separated, e.g. linux/amd64,linux/arm64)'
        required: false
        type: string
        default: linux/amd64,linux/arm64
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  prepare:
    uses: nfrastack/gha/.github/workflows/encrypt.yml@main
    secrets: inherit
  build:
    needs: prepare
    uses: nfrastack/gha/.github/workflows/default_amd64_arm64.yml@main
    with:
      platforms: ${{ inputs.platforms }}
    secrets: inherit
  cleanup:
    needs: build
    uses: nfrastack/gha/.github/workflows/remove_artifacts.yml@main
    secrets: inherit
